language: objective-c
osx_image: xcode10.3
xcode_workspace: ViewGeneratorApp.xcworkspace
xcode_scheme: ViewGeneratorCore
xcode_destination: platform=macOS
before_install:
  - gem install xcpretty
  - gem install cocoapods --pre
  - pod repo update
  - brew update
  - pod install
before_script:
  - set -o pipefail
script:
  - xcodebuild test -workspace ViewGeneratorApp.xcworkspace -scheme ViewGeneratorCore -configuration Debug -destination 'platform=macOS' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
